# Google Cloud Build configuration for DigitalMe
# Builds and deploys to Cloud Run

steps:
  # Build Backend API (Cloud Run optimized)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/digitalme-api:$COMMIT_SHA'
      - '-f'
      - 'src/DigitalMe/Dockerfile.cloudrun'
      - '.'
    id: 'build-api'

  # Build Web Frontend (Cloud Run optimized)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/digitalme-web:$COMMIT_SHA'
      - '-f'
      - 'src/DigitalMe.Web/Dockerfile.cloudrun'
      - '.'
    id: 'build-web'

  # Push Backend API image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/digitalme-api:$COMMIT_SHA'
    id: 'push-api'

  # Push Web Frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/digitalme-web:$COMMIT_SHA'
    id: 'push-web'

  # Deploy Backend API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'digitalme-api'
      - '--image=gcr.io/$PROJECT_ID/digitalme-api:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--add-cloudsql-instances=digitalme-470613:us-central1:digitalme-db'
      - '--set-env-vars=ASPNETCORE_ENVIRONMENT=Production,ASPNETCORE_URLS=http://+:8080,ConnectionStrings__DefaultConnection=Host=/cloudsql/digitalme-470613:us-central1:digitalme-db;Database=digitalme;Username=digitalme;Password=digitalme123;,JWT_KEY=digitalme-super-secret-key-12345678901234567890,JWT:Key=digitalme-super-secret-key-12345678901234567890,JWT__Issuer=DigitalMe,JWT__Audience=DigitalMe,JWT__ExpireHours=24'
      - '--set-secrets=ANTHROPIC_API_KEY=anthropic-api-key:latest,GITHUB_TOKEN=github-token:latest,TELEGRAM_BOT_TOKEN=telegram-bot-token:latest'
      - '--no-cpu-throttling'
      - '--timeout=600'
    id: 'deploy-api'

  # Deploy Web Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'digitalme-web'
      - '--image=gcr.io/$PROJECT_ID/digitalme-web:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=1'
      - '--max-instances=50'
      - '--cpu-throttling'
      - '--concurrency=80'
      - '--set-env-vars=ASPNETCORE_ENVIRONMENT=Production,ASPNETCORE_URLS=http://+:8080,DigitalMe__ApiBaseUrl=https://digitalme-api-llig7ks2ca-uc.a.run.app,DigitalMe__Features__UseRealAuthentication=true'
    id: 'deploy-web'

images:
  - 'gcr.io/$PROJECT_ID/digitalme-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/digitalme-web:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'